# See: /usr/share/doc/mpd/mpdconf.example
pid_file "~/mpd/mpd.pid"
db_file "~/mpd/mpd.db"
state_file "~/mpd/mpdstate"
playlist_directory "~/mpd/playlists"
music_directory "~/music"
auto_update "yes"
audio_output {
  type "pipewire"
  name "mpd pipewire-out"
}
